version: '3'

vars:
  migrVar: internal/storage/migrations

tasks:
  build-auth:
    cmds:
      - |
        BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
        COMMIT=$(git rev-parse HEAD)
        COUNT_COMMIT=$(git rev-list --count HEAD)
        DATE=$(date +"%Y-%m-%d_%H:%M:%S")
        go build -ldflags "-X main.buildVersion=v0.${BRANCH_NAME}.${COUNT_COMMIT} -X main.buildDate=${DATE} -X main.buildCommit=${COMMIT}" -o cmd/auth/auth cmd/auth/main.go
  mockgen:
    cmds:
      - mockgen -destination=internal/mocks/storage/mock_driver.go -package=mocks github.com/rombintu/GophKeeper/internal/storage Driver
      # - mockgen -destination=internal/mocks/storage/mock_grpc.go -package=mocks github.com/rombintu/GophKeeper/internal/proto AuthClient
  protogen:
    cmds:
      - |
        protoc --go_out=. --go_opt=paths=source_relative \
        --go-grpc_out=. --go-grpc_opt=paths=source_relative \
        internal/proto/auth/auth.proto
      - |
        protoc --go_out=. --go_opt=paths=source_relative \
        --go-grpc_out=. --go-grpc_opt=paths=source_relative \
        internal/proto/keeper/keeper.proto
      - |
        protoc --go_out=. --go_opt=paths=source_relative \                                                                                               ─╯
        --go-grpc_out=. --go-grpc_opt=paths=source_relative \
        internal/proto/sync/sync.proto
  mg-up:
    cmds:
      - migrate -path {{.migrVar}} -database $PGX_DB_PATH up
  mg-up-1:
    cmds:
      - migrate -path {{.migrVar}} -database $PGX_DB_PATH up 1
  mg-down-1:
    cmds:
      - migrate -path {{.migrVar}} -database $PGX_DB_PATH down 1
  mg-drop:
    cmds:
      - migrate -path {{.migrVar}} -database $PGX_DB_PATH drop

  prepush:
    cmds:
      - staticcheck ./...
      - errcheck ./...
      - go test -race ./...
      - go test -bench=. ./...

  cover-gen-svg:
    cmds:
      - |
        COVERAGE=$(go tool cover -func=profiles/cover.out | grep total | awk '{print $3}' | sed 's/%//')
        cat <<EOF > profiles/coverage.svg
        <svg xmlns="http://www.w3.org/2000/svg" width="100" height="20">
          <rect width="100" height="20" fill="#555"/>
          <rect width="$COVERAGE" height="20" fill="#4c1"/>
          <text x="5" y="15" fill="#fff" font-family="Arial, sans-serif" font-size="12">$COVERAGE%</text>
        </svg>
        EOF

  cover:
    cmds:
      - go test ./... -coverprofile profiles/dry_cover.out && egrep -v ".pb.go|main|mocks" profiles/dry_cover.out > profiles/cover.out && go tool cover -func=profiles/cover.out
      - task: cover-gen-svg
