name: Staticcheck
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - run: staticcheck ./...